### ISSUE TITLE
This bracket fits

### ISSUE THREAD

**Issue by johndunlap** [schlae/ibm-extender#1]
I recently built an extender card based on your project and it works perfectly! Thank you! While I was ordering parts, I noticed that the BOM for the Extender didn't have a Mouser part number for a bracket. I was able to find one which fits and I thought you might like to add it to the BOM. The Mouser part number is 534-9200-5. Here's a picture of it fitted to my card: https://ibb.co/GHkPnwG

**Comment by schlae** [comment]
Thanks for the suggestion, I've added it to the readme.
